language: scala

scala:
- 2.10.5
- 2.11.4
- 2.11.8

jdk:
- oraclejdk8
- openjdk7

env:
- CI_SCRIPT=ci/run_tests.sh SBT_COMMAND=integration/test
- CI_SCRIPT=ci/run_tests.sh SBT_COMMAND=published/test

matrix:
  include:
  - env: CI_SCRIPT=ci/travis-deploy-docs.py
    jdk: oraclejdk8
    scala: 2.11.8

script:
- $CI_SCRIPT
# Tricks to avoid unnecessary cache updates
#- find $HOME/.sbt -name "*.lock" | xargs rm
#- find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm

sudo: false

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/
