language: scala

matrix:
  include:
  - env: CI_SCRIPT="ci/deploy.py artifacts"
    jdk: oraclejdk8
    scala: 2.11.8


  - env: CI_SCRIPT="ci/run_tests.sh published/test"
    jdk: openjdk7
    scala: 2.10.5
  - env: CI_SCRIPT="ci/run_tests.sh integration/test"
    jdk: openjdk7
    scala: 2.10.5

  - env: CI_SCRIPT="ci/run_tests.sh published/test"
    jdk: oraclejdk8
    scala: 2.10.5
  - env: CI_SCRIPT="ci/run_tests.sh integration/test"
    jdk: oraclejdk8
    scala: 2.10.5


  - env: CI_SCRIPT="ci/run_tests.sh published/test"
    jdk: openjdk7
    scala: 2.11.8
  - env: CI_SCRIPT="ci/run_tests.sh integration/test"
    jdk: openjdk7
    scala: 2.11.8

  - env: CI_SCRIPT="ci/run_tests.sh published/test"
    jdk: oraclejdk8
    scala: 2.11.8
  - env: CI_SCRIPT="ci/run_tests.sh integration/test"
    jdk: oraclejdk8
    scala: 2.11.8


  - env: CI_SCRIPT="ci/deploy.py docs"
    jdk: oraclejdk8
    scala: 2.11.8

script:
- $CI_SCRIPT

notifications:
  email:
    - haoyi.sg@gmail.com

sudo: false
