name: ci-push-validation
on: [push]
jobs:
  unit-11-2_12_12:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - with:
          fetch-depth: 0
      - uses: actions/setup-java@v1
        with:
          java-version: '11'
      - run: ./mill -i unitTest 2.12.12
  unit-8-2_12_12:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - with:
          fetch-depth: 0
      - uses: actions/setup-java@v1
        with:
          java-version: '8'
      - run: ./mill -i unitTest 2.12.12

  unit-8-2_13_3:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - with:
          fetch-depth: 0
      - uses: actions/setup-java@v1
        with:
          java-version: '8'
      - run: ./mill -i unitTest 2.13.3

  integration-11-2_12_12:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - with:
          fetch-depth: 0
      - uses: actions/setup-java@v1
        with:
          java-version: '11'
      - run: ./mill -i integrationTest 2.12.12
  integration-8-2_12_12:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - with:
          fetch-depth: 0
      - uses: actions/setup-java@v1
        with:
          java-version: '8'
      - run: ./mill -i integrationTest 2.12.12

  integration-8-2_13_3:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - with:
          fetch-depth: 0
      - uses: actions/setup-java@v1
        with:
          java-version: '8'
      - run: ./mill -i integrationTest 2.13.3
